### LEER USUARIOS
GET http://localhost:5000/usuarios

###
GET http://localhost:5000/usuarios/6914997ad4d38d3263ac3540

### LEER ACTIVIDADES
GET http://localhost:5000/actividades

###
GET http://localhost:5000/actividades/69149988d4d38d3263ac3547

### LEER RESERVAS
GET http://localhost:5000/reservas

###
GET http://localhost:5000/reservas/

### LEER ASISTENCIAS
GET http://localhost:5000/asistencias

###
GET http://localhost:5000/asistencias/



### CREAR USUARIO
POST http://localhost:5000/usuarios
Content-Type: application/json

{
    "nombre_usuario": "pedro78",
    "contraseña": "abc123..",
    "nombre": "Pedro",
    "apellidos": "Escudero García",
    "dni": "36152233B",
    "telefono": "667132457",
    "email": "pedro78@hotmail.com",
    "rol": "cliente"
}

### CREAR ACTIVIDAD
POST http://localhost:5000/actividades
Content-Type: application/json

{
    "nombre": "Boxeo",
    "descripcion": "Instrucción básica en el noble arte pugilístico",
    "capacidad_maxima": 20,
    "horario": [
        {
            "dia": "Lunes",
            "hora_inicio": "10:00",
            "hora_fin": "11:30"
        },
        {
            "dia": "Miércoles",
            "hora_inicio": "10:00",
            "hora_fin": "11:30"
        }
    ]
}

### CREAR SESION
POST http://localhost:5000/actividades/698b5debf1153ae71ea0c839/sesiones
Content-Type: application/json

### CREAR RESERVA
POST http://localhost:5000/reservas
Content-Type: application/json

{
    "id_usuario": "69823536d6aa1f0615867542",
    "id_sesion": "698de7c1b2cca1f5f61130ce"
}

### CREAR ASISTENCIA
POST http://localhost:5000/asistencias
Content-Type: application/json

{
    "id_usuario": "69823536d6aa1f0615867542",
    "id_sesion": "698b7c36e5489e175856c5a9"
}

### ACTUALIZAR ACTIVIDAD
PUT http://localhost:5000/actividades/698b5debf1153ae71ea0c839
Content-Type: application/json

{
    "nombre": "Boxeo",
    "descripcion": "Instrucción básica en el noble arte de repartir hostias consagradas",
    "capacidad_maxima": 20,
    "horario": [
        {
            "dia": "Lunes",
            "hora_inicio": "10:00",
            "hora_fin": "11:30"
        },
        {
            "dia": "Miércoles",
            "hora_inicio": "10:00",
            "hora_fin": "11:30"
        },
        {
            "dia": "Jueves",
            "hora_inicio": "12:00",
            "hora_fin": "13:30"
        }
    ]
}

### BORRAR ACTIVIDAD
DELETE http://localhost:5000/actividades/698b5ba85fa2824bffe3c24e

### BORRAR RESERVA
DELETE http://localhost:5000/reservas/698b7ecc52633597fdce522f

### BORRAR ASISTENCIA
DELETE http://localhost:5000/asistencias/

### BORRAR SESIÓN
DELETE http://localhost:5000/sesiones/698de7c1b2cca1f5f61130ce