### LEER USUARIOS
GET http://localhost:5000/usuarios

###
GET http://localhost:5000/usuarios/6914997ad4d38d3263ac3540

### LEER ACTIVIDADES
GET http://localhost:5000/actividades

###
GET http://localhost:5000/actividades/69149988d4d38d3263ac3547

### LEER RESERVAS
GET http://localhost:5000/reservas

###
GET http://localhost:5000/reservas/

### LEER ASISTENCIAS
GET http://localhost:5000/asistencias

###
GET http://localhost:5000/asistencias/



### CREAR USUARIO
POST http://localhost:5000/usuarios
Content-Type: application/json

{
    "nombre_usuario": "pedro78",
    "contraseña": "abc123..",
    "nombre": "Pedro",
    "apellidos": "Escudero García",
    "dni": "36152233B",
    "telefono": "667132457",
    "email": "pedro78@hotmail.com",
    "rol": "cliente"
}

### CREAR ACTIVIDAD
POST http://localhost:5000/actividades
Content-Type: application/json

{
    "nombre": "Boxeo",
    "descripcion": "Instrucción básica en el noble arte pugilístico",
    "capacidad_maxima": 20,
    "horario": [
        {
            "dia": "Lunes",
            "hora_inicio": "10:00",
            "hora_fin": "11:30"
        },
        {
            "dia": "Miércoles",
            "hora_inicio": "10:00",
            "hora_fin": "11:30"
        }
    ]
}


### DELETE ACTIVIDAD
DELETE http://localhost:5000/actividades/698b5ba85fa2824bffe3c24e